package es.upm.dit.isst.eacta.dao.test;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Admin1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty( "webdriver.chrome.driver", "/home/isst/chromedriver"); //Dependiendo del sistema operativo
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void admin1() {
    driver.get("http://localhost:3000/login");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("admin1@test.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.name("emailU")).click();
    driver.findElement(By.name("emailU")).sendKeys("alum3@test.com");
    driver.findElement(By.name("rolU")).click();
    driver.findElement(By.name("rolU")).sendKeys("alumno");
    driver.findElement(By.name("NombreU")).click();
    driver.findElement(By.name("NombreU")).sendKeys("alumno3");
    driver.findElement(By.name("passU")).click();
    driver.findElement(By.name("passU")).sendKeys("1234");
    driver.findElement(By.cssSelector(".accionesUsu > button")).click();
    assertThat(driver.switchTo().alert().getText(), is("Usuario añadido con éxito. Recarga la página para ver los cambios."));
    driver.findElement(By.cssSelector(".tablaUsu")).click();
    driver.findElement(By.cssSelector(".tablaUsu > .react-bootstrap-table")).click();
    driver.findElement(By.cssSelector(".header > button")).click();
  }
}
