package es.upm.dit.isst.eacta.dao.test;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Pas1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty( "webdriver.chrome.driver", "/home/isst/chromedriver"); //Dependiendo del sistema operativo
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pas1() {
    driver.get("http://localhost:3000/login");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("pas1@test.com");
    driver.findElement(By.cssSelector(".logContent > div:nth-child(2)")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.xpath("//div[@id=\'box\']/a[2]/button")).click();
    driver.findElement(By.cssSelector(".actaSpace > div")).click();
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
    driver.findElement(By.xpath("(//div[@id=\'box\']/a[2]/button)[2]")).click();
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
  }
}
